### PR TITLE
Fixing failing tests, after merge of gltf related PR

### PR DESCRIPTION
**Pull request by sponce**
I'm not sure why it was not visible before, but here is a fix

### CODE REVIEW

**Comment by sponce** [comment]
@9inpachi I have troubles fixing the tests... On top I do not manage to run them locally. Any idea what goes wrong here ?

**Comment by 9inpachi** [comment]
There is only one test failing now.

You should be able to run them locally by navigating to the `phoenix-event-display` package:

```sh
cd packages/phoenix-event-display
yarn test
```

**Comment by sponce** [comment]
@9inpachi I know that should work... but first it fails because I do not have chrome, and if I try to use chromium I have all tests failing with very weird errors. I gave up for the moment

**Comment by 9inpachi** [comment]
Oh, I realized this PR and #437 are duplicates that fix the same error in different ways?

**Comment by sponce** [comment]
So let's close this one then

**Pull request closed without merging**
