### PR TITLE
Upgrade to yarn modern

### PR DESCRIPTION
**Pull request by EdwardMoyse**
As per issue #545, here I try to update to yarn modern (i.e. yarn > 1.x)

Why this is a good idea: https://yarnpkg.com/getting-started/qa#why-should-you-upgrade-to-yarn-modern

N.B. This does not (yet?) include a migration to plug'n'play: https://yarnpkg.com/getting-started/migration#switching-to-plugnplay

I also removed the deprecated `defaultProject` from angular.json, which mean tweaking `yarn deploy`

Also updated to jsroot 7.3.0, which no longer requires using @9inpachi's special version...

I tried updating other packages, but this caused issues in the CI, so I will try again in a separate PR.

### CODE REVIEW

**Comment by EdwardMoyse** [comment]
Locally this now significantly improves the warnings coming from yarn and angular.  There's a bunch which seem related to [ngx-slider](https://github.com/angular-slider/ngx-slider) not having been updated for a while:
```
emoyse@Beast2:~/phoenix$ yarn explain peer-requirements p2a6d5
➤ YN0000: phoenix-ng@workspace:packages/phoenix-ng provides @angular/common@npm:15.0.4 [107a7] with version 15.0.4, which doesn't satisfy the following requirements:

➤ YN0000: @rp3e11/ngx-slider@npm:13.0.1 [107a7] → ^13.0.2 ✘
```
Not sure what I can do about this!

**Comment by EdwardMoyse** [comment]
Updating jest was perhaps a very bad idea... :-(

**Comment by EdwardMoyse** [comment]
Reverting the package upgrades seems to fix the test. I'll make a separate PR for that.

**Comment by EdwardMoyse** [comment]
@9inpachi - any objections to this going in?

**Comment by 9inpachi** [comment]
This should be a good update. Please go ahead with it!

**Pull request merged**
