### PR TITLE
Unzip-jivexml-from-url

### LINKED ISSUE #505: Open zipped content with url filepath
I've been very confused by this I have not been able to open zipped JiveXML with PhoenixATLAS but now that I'm playing with Phoenix, I think I understand. e.g. this does not work:
`http://localhost:4200/#/atlas?file=assets%2Ffiles%2FJiveXML%2FJiveXML_435678_9781308.zip&type=jivexml`
(you can just zip one of the files in `assets/files/JiveXML` to test this).

The reason is we handle zipped file content in `io-options-dialog.component.ts`
https://github.com/HSF/phoenix/blob/master/packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts#L174

But of course `url-options-manager.ts` doesn't use the same code:
https://github.com/HSF/phoenix/blob/master/packages/phoenix-event-display/src/managers/url-options-manager.ts#L96

I think we should try to share this code better. In the meantime, since this is urgent, I might need to come up with something less elegant.

### PR DESCRIPTION
**Pull request by EdwardMoyse**
Failed attempt to fix #505

@9inpachi - I probably need your help here. I think I've made a complete mess of the promises. :-(

Hopefully you can see what I was trying to do?

It fails with:
```
Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'firstEvent.getAttribute') getEventData@http://localhost:4200/main.js:7384:30 
```

I'll attach a zipped JiveXML file.

### CODE REVIEW

**Comment by EdwardMoyse** [comment]
[JiveXML_435678_9781308.zip](https://github.com/HSF/phoenix/files/9818604/JiveXML_435678_9781308.zip)

**Comment by EdwardMoyse** [comment]
So I gave up trying to get await working.

It's now failing with:
```
Error: Can't find end of central directory : is this a zip file ?
```
I'm not sure why? I tried forcing encode to 64 bit, without luck. :-/

To reproduce:
```
cp JiveXML_435678_9781308.zip docs/assets/files/JiveXML 
```
Then open:
`http://localhost:4200/#/atlas?file=assets%2Ffiles%2FJiveXML%2FJiveXML_336567_2327102923.zip&type=zip`

**Comment by EdwardMoyse** [comment]
> Hi @EdwardMoyse, I will have a look once I get some time. Is it anything urgent?

It would be amazing if you could help me here! It’s fairly urgent, just because it’s taken me so long. It would be wonderful to have something by next Thursday.

**Comment by 9inpachi** [comment]
Cool, rest assured. I will do it on the weekend then. :)

**Comment by EdwardMoyse** [comment]
Amazing @9inpachi - thank you!

**Comment by 9inpachi** [comment]
@EdwardMoyse, it's working now.

**Pull request merged**
