### PR TITLE
Tugboat for PR staging

### PR DESCRIPTION
**Pull request by 9inpachi**
To be merged if #190 is resolved with tugboat as the preference.

Needs HSF org admins to create an account on tugboat.qa and add this repository and enable previews on pull requests.

### CODE REVIEW

**Comment by EdwardMoyse** [comment]
Hi @graeme-a-stewart - would it be possible to get your help with this?

**Comment by graeme-a-stewart** [comment]
Hi @EdwardMoyse - yes, happy to help out with this. Tried to acti vate this on tugboat, which seemed to work, but it also looks like it's tied to my account there. Can you get access or manage it yet?

Screen Shot 2020-12-17 at 10 31 13

**Comment by 9inpachi** [comment]
Hi @graeme-a-stewart 

You can add a user to the project from `Project > Project Settings`. There's a `Users` section there.

image

**Comment by graeme-a-stewart** [comment]
OK thanks for the tip @9inpachi, I invited you and Ed as users.

**Comment by 9inpachi** [comment]
Wonderful! Thanks.

**Comment by 9inpachi** [comment]
Hi @graeme-a-stewart, we are not using Tugboat for PR staging anymore. Could you please delete the project from Tugboat?

The reason is that Tugboat provides 2 GB of free space and our single instance takes up 1.35 GB so having multiple instances isn't really practical for us. We are using surge.sh now.

**Comment by graeme-a-stewart** [comment]
Hi @9inpachi - no problem, I deleted the webhook for Tugboat.

**Comment by graeme-a-stewart** [comment]
And the deployment key as well. I think that's all that's needed to clean up.

**Comment by 9inpachi** [comment]
Thanks a lot @graeme-a-stewart !

**Pull request merged**
